# netlify.toml
[build]
  command = "npm ci && npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  VITE_BACKEND_URL = "https://contract-backend-production-abf2.up.railway.app"